export {Home} from "./Home/Home"
export {NewReleases} from "./NewReleases/NewReleases"
export {TopRated} from "./TopRated/TopRated"
export {Trending} from "./Trending/Trending"
export {Detail} from "./Detail/detail"
export {NotFoundPage} from "./NotFoundPage/NotFoundPage"
export {SearchPage} from "./Search/SearchPage"
export {GenresPage} from "./Genres/GenresPage"